# Generated by Django 5.1.6 on 2025-02-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_upload_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='excels/'),
        ),
    ]
